version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -o ./publish
artifacts:
  files:
    - '**/*'
  base-directory: publish/wwwroot
  name: BuildArtifact